
// Generated by Tramway SDK Code generator

#include "creature.h"
#include "creature.inl"

#include <framework/event.h>
#include <framework/message.h>
	
Creature::Creature(const SharedEntityData& shared_data, const ValueArray& field_array) : Entity(shared_data) {
	ENTITY_IMPLEMENTATION_INITIALIZE
}

void Creature::Register() {
    ENTITY_IMPLEMENTATION_REGISTER
}

name_t Creature::GetType() {
    ENTITY_IMPLEMENTATION_GET_TYPE
}

void Creature::UpdateParameters() {
	mesh->SetLocation(location);
	mesh->SetRotation(rotation);
	
	if (!IsLoaded()) return;
}

void Creature::SetParameters() {
	if (!IsLoaded()) return;
	
	UpdateParameters();
}

void Creature::Load() {
	mesh.make();
	mesh->SetModel(model);
	mesh->Init();
	
	SetFlag(LOADED, true);
	
	UpdateParameters();
}

void Creature::Unload() {
	SetFlag(LOADED, false);
}

void Creature::Serialize() {

}

void Creature::EventHandler(Event& evt) {

}

void Creature::MessageHandler(Message& msg) {

}
	