
// Generated by Tramway SDK Code generator

#include <framework/entity.h>
#include <framework/serialization.h>

#include <framework/event.h>

#include <components/render.h>
#include <components/animation.h>
#include <components/physics.h>

#include <templates/macros.h>

using namespace tram;

class Creature : public Entity {
public:
	Creature(const SharedEntityData&, const ValueArray&);

	TRAM_SDK_ENTITY_NAME("creature")
	
	void UpdateParameters();
	void SetParameters();
	void Load();
	void Unload();
	void Serialize();
	void EventHandler(Event& evt);
	void MessageHandler(Message& msg);
	name_t GetType();
	static void Register();
	
private:
	
	TRAM_SDK_PROPERTY("model", FIELD_SERIALIZE)
	name_t model;
	
	bool rotate_360 = false;
	vec3 head = {0.0f, 0.0f, 0.0f};
	
	EventListener frame;
	
	quat lookat_rot = {1.0f, 0.0f, 0.0f, 0.0f};
	
	Component<RenderComponent> mesh;
	Component<AnimationComponent> armature;
	Component<PhysicsComponent> collider;
};
	