
// Generated by Tramway SDK Code generator

#include "progresscontroller.h"
#include "progresscontroller.inl"

#include <framework/event.h>
#include <framework/message.h>

static ProgressController* controller = nullptr;

ProgressController::ProgressController() : Entity("progress") {
	
}

void ProgressController::Init() {
    controller = new ProgressController;
}

name_t ProgressController::GetType() {
    ENTITY_IMPLEMENTATION_GET_TYPE
}

void ProgressController::UpdateParameters() {
	if (!IsLoaded()) return;
}

void ProgressController::SetParameters() {
	if (!IsLoaded()) return;
	
	UpdateParameters();
}

void ProgressController::Load() {
	SetFlag(LOADED, true);
}

void ProgressController::Unload() {
	SetFlag(LOADED, false);
}

void ProgressController::Serialize() {

}

void ProgressController::EventHandler(Event& evt) {

}

void ProgressController::MessageHandler(Message& msg) {

}
	