
// Generated by Tramway SDK Code generator
// READ ONLY! Any and all changes will be overwritten!
	
enum {
FIELD_NONE
};

#define ENTITY_IMPLEMENTATION_INITIALIZE \


#define ENTITY_IMPLEMENTATION_REGISTER  \
Entity::RegisterType( \
	"progress-controller",  \
	[](const SharedEntityData& a, const ValueArray& b) -> Entity* { return new ProgressController(a, b); }, \
	[](Entity* a) { delete a; }, \
	{ \
 \
	} \
);

#define ENTITY_IMPLEMENTATION_GET_TYPE return "progress-controller";

	