
// Generated by Tramway SDK Code generator

#include <framework/entity.h>
#include <framework/serialization.h>

#include <framework/event.h>

#include <templates/macros.h>

using namespace tram;

enum GameState {
	STATE_NORMAL,
	STATE_ITEM
};

class ProgressController : public Entity {
public:
	ProgressController();

	static void Init();
	
	TRAM_SDK_ENTITY_NAME("progress-controller")
	
	void UpdateParameters();
	void SetParameters();
	void Load();
	void Unload();
	void Serialize();
	void EventHandler(Event& evt);
	void MessageHandler(Message& msg);
	name_t GetType();
	
	GameState GetState() {
		return state;
	}
	
	void SetNPCDialog(std::string dialog); 
	void SetNotification(std::string notif); 
	
private:
	GameState state = STATE_NORMAL;
	
	std::string npc_text = "";
	int npc_progress = 0;
	int npc_length = 0;
	
	std::string notif_text = "";
	int notif_progress = 0;
	int notif_length = 0;
	
	EventListener frame;
	EventListener keypress;
};
	